# Generated by Django 4.0.1 on 2022-01-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220117_1812'),
        ('store', '0004_auto_20210610_1442'),
    ]

    operations = [
    ]
